src/components/OrderHistory.jsx
src/pages/Profile.jsx

- Make order history component
- Make responsive design

feat: Order History Component

---

src/components/DropdownMobile.jsx
src/components/Navbar.jsx
src/pages/Home.jsx
src/pages/Movie.jsx
src/pages/MovieDetail.jsx
src/pages/Order.jsx

some update Navigate

---

src/Router.jsx
src/components/PaymentModal.jsx
src/pages/Payment.jsx

-payment page,
-responsive page
-payment modal,  with copy text Virtual account
-update route

payment page, paymentmodal, route

---

.gitignore
src/components/OrderHistory.jsx
src/utils/getDate.js

- Integrate order history with /customer/order-history endpoint

Update: /order-history

---

src/components/CardMovie.jsx
src/pages/Movie.jsx
src/pages/MovieDetail.jsx

- fix movie card integration
- integrate get /movie-cinema 
- integrate get /movie-location

update: /movie /movie/:id

---

src/pages/MovieDetail.jsx

- make dynamic location component

update: location component

---

src/pages/MovieDetail.jsx

-fix bg movie detail
-fix img movie detail n responsive

movie detail

---

src/pages/Movie.jsx

search movie

---

src/pages/TicketResult.jsx

- integration of backend & frontend at ticket result

feat: integration of backend & frontend at ticket result

---

src/components/ItemSeat.jsx
src/components/OrderHistory.jsx
src/components/PaymentModal.jsx
src/pages/MovieDetail.jsx
src/pages/Order.jsx
src/pages/Payment.jsx
src/pages/Profile.jsx
src/utils/getDate.js

feat: order

---

src/Router.jsx
src/components/InfoSeat.jsx
src/components/ItemSeat.jsx
src/components/OrderHistory.jsx
src/components/PrivateRoute.jsx
src/pages/Order.jsx

- make private route for loged user

feat: private route

---

src/pages/Movie.jsx

filter list movie

---

src/Router.jsx
src/components/OrderHistory.jsx
src/components/PaymentModal.jsx
src/pages/TicketResult.jsx

- update ticket result
- integrate check payment with /customer/update-paid-status/58
- integrate /ticketresult with  /customer/history-order/ticket?orderId=?

update: ticket result

---

src/pages/Order.jsx

update: order

---

src/components/OrderHistory.jsx
src/pages/Profile.jsx

update: history order

---

src/pages/ListMovie.jsx

udpate: /admin/listmovie

---

src/pages/ListMovie.jsx
src/pages/Movie.jsx

-Update List Movie,
-Pagination
-Error Handling movie not show
-minor Update

Update List Movie,Pagination,Error Handling movie not show n minor update

---

package-lock.json
package.json
src/pages/AddMovie.jsx
tailwind.config.js

- select react in ratings
- textare in synopsis

feat: addMovie

---

src/pages/ListMovie.jsx

update: /admin/listmovie

---

package-lock.json
package.json
src/pages/ListMovie.jsx

list movie update
pagination,
delete movie

List Movie

---

src/components/SalesChart.jsx
src/components/TicketChart.jsx
src/pages/Dashboard.jsx

- chart in sales
- chart in ticket

feat chart

---

src/pages/AddMovie.jsx

- integrate addmovie with /admin/add-new/movie endpoint

update: /admin/addmovie

---

src/Router.jsx
src/pages/Unauthorized.jsx

feat: /unauthorized

---

src/components/Navbar.jsx
src/pages/AddMovie.jsx
src/pages/ListMovie.jsx

- add navigation for admin
- add error message ford /addmoviee

update: /addmovie errmessage

---

src/pages/MovieDetail.jsx

rev Detail Movie coming soon not show order

Update: rev Detail Movie Coming

---

src/pages/Profile.jsx

feat: alert success and error

---

src/pages/Movie.jsx

update:
loading fetch data
handling error no data from server
handling error filter by genre
handling error search

update loading, handling all error

---

src/pages/ListMovie.jsx

fix Delete list cinema
Loading cinema

fix Delete Cinema
